#include "global.h"
#include "charater.h"
#include "scene.h"
#include "enemy.h"
#include "collider.h"
#include "scorecount.h"
#include "treasure.h"
#include "video_end_game.h"
#include "math.h"
#include "menuclick.h"
#include "bigboss.h"
#include "bigbosschara.h"
#include "bigbossbullet.h"
int Game_establish();
void game_init();
void game_begin();
void game_update();
int process_event();
void game_draw();
int game_run();
void game_destroy();
